### PR TITLE
Support for Coda font

### PR DESCRIPTION
**Pull request by mattdbr**
I think this is better please tell me if I made another mistake :laughing:

### CODE REVIEW

**Comment by therealklanni** [comment]
So we're removing Iceland completely? I'll have to pull this locally and check that everything still lines up properly. The text positioning was very precise and based on the font (width, kerning, height, etc).

**Comment by mattdbr** [comment]
It looked alright with the previous pull. Just check though. What was
Iceland used for that coda can't be used for. In the end it's a simple
design choice I guess.

**Comment by therealklanni** [comment]
I'm sure it's fine, just wanted to double check since the fonts are
different. :)

**Comment by therealklanni** [comment]
Sorry for the delay. Finally got a chance to take a look at this PR. It's going to need some additional tweaking to get the Coda font to work properly before it can be merged. Below is an example:

screen shot 2015-04-09 at 5 27 48 pm

**Pull request closed without merging**
